// ESLint flat config for Poly Oracle.
//
// Philosophy: low-noise, high-signal BUG CATCHER — not a style checker.
//   - The recommended ruleset (dupe keys, unreachable code, const reassignment,
//     use-isnan, etc.) stays as ERRORS — each one is a probable real bug.
//   - no-unused-vars / no-undef are WARNINGS so they never block; this is a large
//     vanilla-JS codebase with many cross-file globals.
//   - No formatting rules. We deliberately do NOT run Prettier here: reformatting
//     a 16k-line file would create a huge, risky diff.
//
// Only the source-of-truth root JS files are linted. `www/` is generated by
// `npm run prepare:web` and must never be linted.

import js from "@eslint/js";
import globals from "globals";

// Shared bug-catcher rules: recommended-as-errors, with the noisy ones softened.
const bugCatcherRules = {
  ...js.configs.recommended.rules,
  "no-unused-vars": "warn",
  "no-undef": "warn",
  "no-empty": "warn",
  "no-constant-condition": ["warn", { checkLoops: false }],
  "no-prototype-builtins": "off",
  // Code-quality, not crash/logic bugs — keep them visible but out of the error
  // tier so a real error always means a probable bug.
  "no-useless-assignment": "warn",
  "no-useless-escape": "warn",
};

export default [
  {
    // Never lint generated, vendored, native, or local-only output.
    ignores: [
      "www/**",
      "node_modules/**",
      "ios/**",
      "android/**",
      "backups/**",
      "local/**",
      "api/**",
      "firebase-config.js",
      "firebase-config.example.js",
      "updated script.js",
      "**/*.bak",
    ],
  },

  {
    // Plain <script> files sharing one global scope (functions defined in one
    // file are referenced in another — hence no-undef is a warning, not an error).
    files: [
      "script.js",
      "galaxyBackground.js",
      "ufo-death-effect.js",
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.es2021,
        // Libraries / cross-file globals loaded at runtime.
        PIXI: "readonly",
        Capacitor: "readonly",
        firebase: "readonly",
        // Add genuine cross-file shared functions here as the first lint run
        // surfaces them, so no-undef warnings stay meaningful.
      },
    },
    rules: bugCatcherRules,
  },

  {
    // ES module: <script type="module" src="pixiRenderer.js">
    files: ["pixiRenderer.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.es2021,
        PIXI: "readonly",
      },
    },
    rules: bugCatcherRules,
  },

  {
    // Node build helper (CommonJS, run via `node resizeCommander.js`).
    files: ["resizeCommander.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: { ...globals.node },
    },
    rules: bugCatcherRules,
  },
];
